package vt.db.model.entity;

import vt.db.model.entity.base.Entity;
/***
 * Generated 2017-09-26 19:55:22 by Hibernate Tools 5.1.0.Alpha1.
 * Department generated by hbm2java.
 * 
 * Class represents company departments. 
 * @author Mateusz Mucha
 */
public class Department extends Entity {
	private static final long serialVersionUID = -6065174214450498585L;
	private String depName;

	
	public Department() {
		super();
	}
	public Department(String depName) {
		super();
		this.depName = depName;
	}

	
	public String getDepName() {
		return this.depName;
	}
	public void setDepName(String depName) {
		this.depName = depName;
	}
}