package vt.db.model.entity;

import vt.db.model.entity.base.Entity;
/***
 * Generated 2017-09-26 19:55:22 by Hibernate Tools 5.1.0.Alpha1.
 * FreeDays generated by hbm2java.
 * 
 * Class represents non-working days in current year. 
 * @author Mateusz Mucha
 */
public class FreeDays extends Entity {
	private static final long serialVersionUID = -6860986496270908990L;
	private Integer freeDay;
	private Integer freeMonth;
	private Integer freeYear;

	
	public FreeDays() {
		super();
	}
	public FreeDays(Integer freeDay, Integer freeMonth, Integer freeYear) {
		super();
		this.freeDay = freeDay;
		this.freeMonth = freeMonth;
		this.freeYear = freeYear;
	}

	
	public Integer getFreeDay() {
		return this.freeDay;
	}
	public void setFreeDay(Integer freeDay) {
		this.freeDay = freeDay;
	}
	public Integer getFreeMonth() {
		return this.freeMonth;
	}
	public void setFreeMonth(Integer freeMonth) {
		this.freeMonth = freeMonth;
	}
	public Integer getFreeYear() {
		return this.freeYear;
	}
	public void setFreeYear(Integer freeYear) {
		this.freeYear = freeYear;
	}
}