package vt.db.model.entity;

import vt.db.model.entity.base.Entity;
/***
 * Generated 2017-09-26 19:55:22 by Hibernate Tools 5.1.0.Alpha1.
 * Position generated by hbm2java.
 * 
 * Class represents company work positions. 
 * @author Mateusz Mucha
 */
public class Position extends Entity {
	private static final long serialVersionUID = 8899862037850331650L;
	private String positionName;
	private Integer positionDepartmentId;
	
	
	public Position() {
		super();
	}
	public Position(String positionName, Integer positionDepartmentId) {
		super();
		this.positionName = positionName;
		this.positionDepartmentId = positionDepartmentId;
	}
	

	public String getPositionName() {
		return this.positionName;
	}
	public void setPositionName(String posName) {
		this.positionName = posName;
	}
	public Integer getPositionDepartmentId() {
		return this.positionDepartmentId;
	}
	public void setPositionDepartmentId(Integer positionDepartmentId) {
		this.positionDepartmentId = positionDepartmentId;
	}
}