package vt.db.model.entity;
// default package
// Generated 2017-09-26 19:55:22 by Hibernate Tools 5.1.0.Alpha1

/**
 * VtDepartment generated by hbm2java
 */
public class VtDepartment implements java.io.Serializable {

	private Integer idDepartment;
	private String depName;

	public VtDepartment() {
	}

	public VtDepartment(String depName) {
		this.depName = depName;
	}

	public Integer getIdDepartment() {
		return this.idDepartment;
	}

	public void setIdDepartment(Integer idDepartment) {
		this.idDepartment = idDepartment;
	}

	public String getDepName() {
		return this.depName;
	}

	public void setDepName(String depName) {
		this.depName = depName;
	}

}
