package vt.db.model.entity;
// default package
// Generated 2017-09-26 19:55:22 by Hibernate Tools 5.1.0.Alpha1

/**
 * VtEmployee generated by hbm2java
 */
public class VtEmployee implements java.io.Serializable {

	private Integer idEmployee;
	private String empFirstName;
	private String empLastName;
	private String empBirthDate;
	private String empAvatar;
	private Integer empDepartmentId;
	private Integer empPositionId;
	private Integer empManagerId;
	private Integer empIsManager;
	private String empEvidenceNumber;
	private Double empAreaOfWork;
	private Integer empWorkingHoursPerDay;
	private String empFirstWorkDay;

	public VtEmployee() {
	}

	public VtEmployee(String empFirstName, String empLastName, String empBirthDate, String empAvatar,
			Integer empDepartmentId, Integer empPositionId, Integer empManagerId, Integer empIsManager,
			String empEvidenceNumber, Double empAreaOfWork, Integer empWorkingHoursPerDay, String empFirstWorkDay) {
		this.empFirstName = empFirstName;
		this.empLastName = empLastName;
		this.empBirthDate = empBirthDate;
		this.empAvatar = empAvatar;
		this.empDepartmentId = empDepartmentId;
		this.empPositionId = empPositionId;
		this.empManagerId = empManagerId;
		this.empIsManager = empIsManager;
		this.empEvidenceNumber = empEvidenceNumber;
		this.empAreaOfWork = empAreaOfWork;
		this.empWorkingHoursPerDay = empWorkingHoursPerDay;
		this.empFirstWorkDay = empFirstWorkDay;
	}

	public Integer getIdEmployee() {
		return this.idEmployee;
	}

	public void setIdEmployee(Integer idEmployee) {
		this.idEmployee = idEmployee;
	}

	public String getEmpFirstName() {
		return this.empFirstName;
	}

	public void setEmpFirstName(String empFirstName) {
		this.empFirstName = empFirstName;
	}

	public String getEmpLastName() {
		return this.empLastName;
	}

	public void setEmpLastName(String empLastName) {
		this.empLastName = empLastName;
	}

	public String getEmpBirthDate() {
		return this.empBirthDate;
	}

	public void setEmpBirthDate(String empBirthDate) {
		this.empBirthDate = empBirthDate;
	}

	public String getEmpAvatar() {
		return this.empAvatar;
	}

	public void setEmpAvatar(String empAvatar) {
		this.empAvatar = empAvatar;
	}

	public Integer getEmpDepartmentId() {
		return this.empDepartmentId;
	}

	public void setEmpDepartmentId(Integer empDepartmentId) {
		this.empDepartmentId = empDepartmentId;
	}

	public Integer getEmpPositionId() {
		return this.empPositionId;
	}

	public void setEmpPositionId(Integer empPositionId) {
		this.empPositionId = empPositionId;
	}

	public Integer getEmpManagerId() {
		return this.empManagerId;
	}

	public void setEmpManagerId(Integer empManagerId) {
		this.empManagerId = empManagerId;
	}

	public Integer getEmpIsManager() {
		return this.empIsManager;
	}

	public void setEmpIsManager(Integer empIsManager) {
		this.empIsManager = empIsManager;
	}

	public String getEmpEvidenceNumber() {
		return this.empEvidenceNumber;
	}

	public void setEmpEvidenceNumber(String empEvidenceNumber) {
		this.empEvidenceNumber = empEvidenceNumber;
	}

	public Double getEmpAreaOfWork() {
		return this.empAreaOfWork;
	}

	public void setEmpAreaOfWork(Double empAreaOfWork) {
		this.empAreaOfWork = empAreaOfWork;
	}

	public Integer getEmpWorkingHoursPerDay() {
		return this.empWorkingHoursPerDay;
	}

	public void setEmpWorkingHoursPerDay(Integer empWorkingHoursPerDay) {
		this.empWorkingHoursPerDay = empWorkingHoursPerDay;
	}

	public String getEmpFirstWorkDay() {
		return this.empFirstWorkDay;
	}

	public void setEmpFirstWorkDay(String empFirstWorkDay) {
		this.empFirstWorkDay = empFirstWorkDay;
	}

}
