package vt.db.model.entity;
// default package
// Generated 2017-09-26 19:55:22 by Hibernate Tools 5.1.0.Alpha1

/**
 * VtFreeDays generated by hbm2java
 */
public class VtFreeDays implements java.io.Serializable {

	private int idFree;
	private Integer freeDay;
	private Integer freeMonth;
	private Integer freeYear;

	public VtFreeDays() {
	}

	public VtFreeDays(int idFree) {
		this.idFree = idFree;
	}

	public VtFreeDays(int idFree, Integer freeDay, Integer freeMonth, Integer freeYear) {
		this.idFree = idFree;
		this.freeDay = freeDay;
		this.freeMonth = freeMonth;
		this.freeYear = freeYear;
	}

	public int getIdFree() {
		return this.idFree;
	}

	public void setIdFree(int idFree) {
		this.idFree = idFree;
	}

	public Integer getFreeDay() {
		return this.freeDay;
	}

	public void setFreeDay(Integer freeDay) {
		this.freeDay = freeDay;
	}

	public Integer getFreeMonth() {
		return this.freeMonth;
	}

	public void setFreeMonth(Integer freeMonth) {
		this.freeMonth = freeMonth;
	}

	public Integer getFreeYear() {
		return this.freeYear;
	}

	public void setFreeYear(Integer freeYear) {
		this.freeYear = freeYear;
	}

}
