package vt.db.model.entity;
// default package
// Generated 2017-09-26 19:55:22 by Hibernate Tools 5.1.0.Alpha1

/**
 * VtPosition generated by hbm2java
 */
public class VtPosition implements java.io.Serializable {

	private Integer idPosition;
	private String posName;
	private Integer posDepartmentId;

	public VtPosition() {
	}

	public VtPosition(String posName, Integer posDepartmentId) {
		this.posName = posName;
		this.posDepartmentId = posDepartmentId;
	}

	public Integer getIdPosition() {
		return this.idPosition;
	}

	public void setIdPosition(Integer idPosition) {
		this.idPosition = idPosition;
	}

	public String getPosName() {
		return this.posName;
	}

	public void setPosName(String posName) {
		this.posName = posName;
	}

	public Integer getPosDepartmentId() {
		return this.posDepartmentId;
	}

	public void setPosDepartmentId(Integer posDepartmentId) {
		this.posDepartmentId = posDepartmentId;
	}

}
