package vt.db.model.entity;
// default package
// Generated 2017-09-26 19:55:22 by Hibernate Tools 5.1.0.Alpha1

/**
 * VtVacation generated by hbm2java
 */
public class VtVacation implements java.io.Serializable {

	private Integer idVacation;
	private Integer vacYear;
	private Integer vacDaysLeft;
	private int vacType;
	private int vacEmployeeId;

	public VtVacation() {
	}

	public VtVacation(int vacType, int vacEmployeeId) {
		this.vacType = vacType;
		this.vacEmployeeId = vacEmployeeId;
	}

	public VtVacation(Integer vacYear, Integer vacDaysLeft, int vacType, int vacEmployeeId) {
		this.vacYear = vacYear;
		this.vacDaysLeft = vacDaysLeft;
		this.vacType = vacType;
		this.vacEmployeeId = vacEmployeeId;
	}

	public Integer getIdVacation() {
		return this.idVacation;
	}

	public void setIdVacation(Integer idVacation) {
		this.idVacation = idVacation;
	}

	public Integer getVacYear() {
		return this.vacYear;
	}

	public void setVacYear(Integer vacYear) {
		this.vacYear = vacYear;
	}

	public Integer getVacDaysLeft() {
		return this.vacDaysLeft;
	}

	public void setVacDaysLeft(Integer vacDaysLeft) {
		this.vacDaysLeft = vacDaysLeft;
	}

	public int getVacType() {
		return this.vacType;
	}

	public void setVacType(int vacType) {
		this.vacType = vacType;
	}

	public int getVacEmployeeId() {
		return this.vacEmployeeId;
	}

	public void setVacEmployeeId(int vacEmployeeId) {
		this.vacEmployeeId = vacEmployeeId;
	}

}
