package vt.db.model.entity;
// default package
// Generated 2017-09-26 19:55:22 by Hibernate Tools 5.1.0.Alpha1

/**
 * VtVacationType generated by hbm2java
 */
public class VtVacationType implements java.io.Serializable {

	private Integer idVacationType;
	private String vacTypeName;
	private Integer vacTypeMaxDays;

	public VtVacationType() {
	}

	public VtVacationType(String vacTypeName, Integer vacTypeMaxDays) {
		this.vacTypeName = vacTypeName;
		this.vacTypeMaxDays = vacTypeMaxDays;
	}

	public Integer getIdVacationType() {
		return this.idVacationType;
	}

	public void setIdVacationType(Integer idVacationType) {
		this.idVacationType = idVacationType;
	}

	public String getVacTypeName() {
		return this.vacTypeName;
	}

	public void setVacTypeName(String vacTypeName) {
		this.vacTypeName = vacTypeName;
	}

	public Integer getVacTypeMaxDays() {
		return this.vacTypeMaxDays;
	}

	public void setVacTypeMaxDays(Integer vacTypeMaxDays) {
		this.vacTypeMaxDays = vacTypeMaxDays;
	}

}
